package uz.ikhtidev.bukharatelefonbot.utils;

public interface TelegramUserStep {
    String START = "/start";
    String SELECT_CREATE_POST_OR_ADMIN = "SELECT_CREATE_POST_OR_ADMIN";
    String ENTER_PHONE_NAME = "ENTER_PHONE_NAME";
    String ENTER_PHONE_MEMORY = "ENTER_PHONE_MEMORY";
    String ENTER_PHONE_YEAR = "ENTER_PHONE_YEAR";
    String ENTER_PHONE_COLOR = "ENTER_PHONE_COLOR";
    String ENTER_PHONE_HAS_DOC = "ENTER_PHONE_HAS_DOC";
    String ENTER_PHONE_CONDITION = "ENTER_PHONE_CONDITION";
    String ENTER_PHONE_CHARGE = "ENTER_PHONE_CHARGE";
    String ENTER_PHONE_IS_REPLACE = "ENTER_PHONE_IS_REPLACE";
    String ENTER_PHONE_PRICE = "ENTER_PHONE_PRICE";
    String ENTER_PHONE_ADDRESS = "ENTER_PHONE_ADDRESS";
    String ENTER_OWNER_PHONE_NUMBER = "ENTER_OWNER_PHONE_NUMBER";
    String ENTER_PHONE_IMAGE = "ENTER_PHONE_IMAGE";
    String SEND_POST_TO_ADMIN_FOR_PUBLISH = "SEND_POST_TO_ADMIN_FOR_PUBLISH";
    String WAITING_MODERATOR = "WAITING_MODERATOR";
    String ADMIN_FULL_ACCESS = "ADMIN_FULL_ACCESS";
}